### ISSUE TITLE
Base in Mac, diff in Jenkins (actual)

### ISSUE THREAD

**Issue by hongdeyuan** [cypress-visual-regression/cypress-visual-regression#191]
Base in Mac, diff in Jenkins (actual), why diff failed?

- window-size: 1440,900;
- viewportWidth,viewportHeight: 1440, 900
```
viewportWidth: 1440,
viewportHeight: 900,
e2e: {
   setupNodeEvents(on, config) {
      getCompareSnapshotsPlugin(on, config);
      on('before:browser:launch', (browser, launchOptions) => {
        // https://on.cypress.io/browser-launch-api

        // the browser width and height we want to get
        if (browser.name === 'chrome' && browser.isHeadless) {
          launchOptions.args.push('--window-size=1440,900');
        }

        return launchOptions;
      });
      return config;
    },
}
```

- Base in Mac, diff in Mac ，is ok;
   - The webpage is static：Web pages are static and unchanging content；
   - mac: cypress 12.7.0
![image](https://user-images.githubusercontent.com/37143703/233584092-14d7b1a7-9c3f-4c22-bb7c-e7062eefc0a5.png)

- Base in Mac, diff in Jenkins (actual), failed
  - Jenkins: cypress image: cypress-included:12.7.0
  - mac: cypress 12.7.0

![image](https://user-images.githubusercontent.com/37143703/233584881-cdf1e663-1487-45bd-b0ea-6c38ebb203e8.png)

**Comment by Radik24** [comment]
Hi, I see similar issue in my Gitlab CI

cypress: ^12.11.0
cypress-visual-regression: ^3.0.0

My default is 0.05.

![image](https://user-images.githubusercontent.com/23722745/235485021-b31d7a0f-50ba-4f78-b20a-b8f2ddf29081.png)


I can solve ~90% of tests when I raise threshold to 0.075, but few of them are 0.1+.

Also I found in logs:
`[3592:0501/155410.975188:ERROR:gl_utils.cc(319)] [.WebGL-0x1554044a0000]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels`

Any ideas?

Thanks

**Comment by Radik24** [comment]
@hongdeyuan I figured out I have two kinds of issues:

- different colors - solved by passing `--force-color-profile=srgb` to chrome args. Firefox was fine in my case
- fonts - somewhere on the internet I found that css font can be rendered differently on multiple machines (mac/linux/pc). I 'solved' it on UI framework's side

I discarted electron as it makes real mess and I cannot fix it with flags.

**Comment by hongdeyuan** [comment]
> @hongdeyuan I figured out I have two kinds of issues:
> 
> * different colors - solved by passing `--force-color-profile=srgb` to chrome args. Firefox was fine in my case
> * fonts - somewhere on the internet I found that css font can be rendered differently on multiple machines (mac/linux/pc). I 'solved' it on UI framework's side
> 
> I discarted electron as it makes real mess and I cannot fix it with flags.

Wow, it looks good；
- `--force-color-profile=srgb`： Force the colour profile - should reduce colour differences in diffs between MacOS and Linux (CI)

  the second question, perhaps you can try `--font-render-hinting=none`, it force font rendering - should reduce differences in diffs between MacOS and Linux (CI)

**Comment by hongdeyuan** [comment]
> @hongdeyuan I figured out I have two kinds of issues:
> 
> * different colors - solved by passing `--force-color-profile=srgb` to chrome args. Firefox was fine in my case
> * fonts - somewhere on the internet I found that css font can be rendered differently on multiple machines (mac/linux/pc). I 'solved' it on UI framework's side
> 
> I discarted electron as it makes real mess and I cannot fix it with flags.
In addition to the two issues you described, there is also a possible cause; Missing expected fonts in Linux environment resulting in page garbled code
As described by this issue ：https://github.com/cypress-io/cypress-docker-images/issues/109?ref=cypress.io

**Comment by hongdeyuan** [comment]
> Another alternative (a bit painful) might be to generate base images by running the same image using docker on your Mac and then copy them over to your code from the container.

@Zaista 
A better method is to use dcoke images to run cypress/include for visual Regression testing, but it seems that both base and actual are using dockers and cannot solve the problem; Although using `--font-render-hinting=none` can reduce errors, inconsistent diffs can still be found, although it is accidental;

Perhaps there are other reasons for this, as discussed in this issue ：https://github.com/cypress-io/cypress/issues/19354

**Comment by radoslavirha** [comment]
@hongdeyuan you're right, docker does not solve the issue. Result is better it seems, but still not ok.
